### ISSUE TITLE
Update to new API endpoints

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/abondance#10]
API endpoints have been restructured. Abondance should use the new structure

**Comment by ritikBhandari** [comment]
hi,
Can I solve this issue?

**Comment by romain-fontugne** [comment]
Yes, sure. I think this concerns the delay, forwarding, and disconnect.

**Comment by ritikBhandari** [comment]
So these are the new endpoints. Right?

**Comment by romain-fontugne** [comment]
yes, but actually there is even more: https://ihr.iijlab.net/ihr/en-us/api

**Comment by ritikBhandari** [comment]
> yes, but actually there is even more: https://ihr.iijlab.net/ihr/en-us/api

So do we have to categorize these are the endpoints into 'delay', 'forwarding' and 'disconnect'?

**Comment by romain-fontugne** [comment]
Currently:
- delay in abondance corresponds to data available at https://ihr.iijlab.net/ihr/api/link/delay/
- forwarding in abondance corresponds to data available at https://ihr.iijlab.net/ihr/api/link/forwarding/
- disconnect in abondance corresponds to data available at https://ihr.iijlab.net/ihr/api/disco/events/

I suggest that we rename files/objects in abondance to reflect better the corresponding API endpoint. For example link_forwrading.py, link_delay.py, disco_events.py

**Comment by ritikBhandari** [comment]
@romain-fontugne I have opened a pull request regarding the same. Please look into it so that if there's still some misinterpretation I can work on it again.

**Comment by romain-fontugne** [comment]
Thanks that's good!
