### ISSUE TITLE
Code breaks when trying to log that no hegemony results are found

### ISSUE THREAD

**Issue by talhajavedmukhtar** [InternetHealthReport/abondance#9]
**This is the error trace:**
_File "/usr/local/lib/python3.7/site-packages/abondance-0.0.1-py3.7.egg/ihr/hegemony.py", line 144, in get_results
NameError: name 'params' is not defined_

**I think the 'params' that is being invoked is local to the query_api() function, and is inaccessible in get_results().**

**Comment by Toppyo** [comment]
For records, 32842 as originasn(Iburst) to query its hegemony during 2019-01-01~2019-01-03 will return error messages the same as above. By checking the website-- https://ihr.iijlab.net/ihr/32842/asn/?af=4&date=2019-01-05&last=7, no hegemony is observed on those days.

**Comment by AhnafSulficar** [comment]
![image](https://user-images.githubusercontent.com/89102131/226595141-31250e6f-cbe7-4830-9446-ffb8500cc152.png)
It is workiing fine.

**Comment by romain-fontugne** [comment]
thanks, I'm closing this
